name: saving
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  animations: ^2.0.11
  bcrypt: ^1.1.3
  cupertino_icons: ^1.0.6
  faker: ^2.2.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  go_router: ^14.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  skeletonizer: ^1.4.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf
